[package]
name = "ide_framework"
version = "0.1.0"
edition = "2024"

[lib]
name = "ide_framework"
crate-type = ["cdylib", "rlib"]

[dependencies]
core-std-lib = { workspace = true }
core-module-lib = { workspace = true }
async-trait = "0.1.88"
