// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TMap = Array<[string, TValue]>;

export type TValue =
  | { "int": number }
  | { "float": number }
  | { "bool": boolean }
  | { "str": string }
  | { "list": Array<TValue> }
  | { "obj": Array<[string, TValue]> };
