// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TValue = { "Int": number } | { "Float": number } | { "Bool": boolean } | { "Str": string } | { "List": Array<TValue> } | { "Obj": Array<[string, TValue]> };
