[package]
name = "ide_pm"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
core-std-lib = { workspace = true }
core-module-lib = { workspace = true }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
