setup:
  stage: .pre
  image: rust
  script:
    - apt install libwebkit2gtk-4.0-dev build-essential libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev

test:
  stage: test
  image: rust
  script:
    - cd src-tauri
    - cargo test

build:
  stage: build
  image: rust
  script:
    - cd src-tauri
    - cargo build --release
