setup:
  stage: .pre
  image: rust
  script:
    - apt install build-essential libssl-dev librsvg2-dev

test:
  stage: test
  image: rust
  script:
    - cd src-tauri
    - cargo test

build:
  stage: build
  image: rust
  script:
    - cd src-tauri
    - cargo build --release
