stages:
  - linting
  - test
  - svn
  - build

default:
  image: neelzee/tauri_img

variables:
  CORE_OUT_DIR: "nmide-core/src-tauri/target/release/*"

rust_test:
  stage: test
  script:
    - echo "TODO"

js_test:
  stage: test
  script:
    - echo "TODO"

pts:
  stage: svn
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
  dependencies:
    - "js_test"
    - "rust_test"
  script:
    - ./pushToSvn.sh

pdf-build:
  state: build
  dependencies:
    - pts
  when: manual
  only:
    - main
  script:
    - just pdf
  artifacts:
    when: on_success
    access: all
    paths:
      - nmide-thesis/*.pdf

windows-build:
  stage: build
  dependencies:
    - "pts"
  when: manual
  only:
    - main
  script:
    - echo "Needs a windows image"
  artifacts:
    when: on_success
    access: all
    paths:
      - $OUT_DIR

debian-build:
  stage: build
  dependencies:
    - "pts"
  when: manual
  only:
    - main
  script:
    - just build-release
  artifacts:
    when: on_success
    access: all
    paths:
      - $OUT_DIR

mac-build:
  stage: build
  dependencies:
    - "pts"
  when: manual
  only:
    - main
  script:
    - echo "TODO"
  artifacts:
    when: on_success
    access: all
    paths:
      - $OUT_DIR
