setup:
  stage: .pre
  image: rust
  script:
    - apt-get -y install librust-gdk4-x11-sys-dev

test:
  stage: test
  image: rust
  script:
    - cd src-tauri
    - cargo test

build:
  stage: build
  image: rust
  script:
    - cd src-tauri
    - cargo build --release
