setup:
  stage: .pre
  image: rust
  script:
    - apt-get update -qy
    - apt-get gdk-3.0

test:
  stage: test
  image: rust
  script:
    - cd src-tauri
    - cargo test

build:
  stage: build
  image: rust
  script:
    - cd src-tauri
    - cargo build --release
