stages:
  - linting
  - test
  - push to svn
  - build

linting:
  stage: linting
  image: neelzee/tauri_img
  script:
    - rustup component add clippy
    - cd src-tauri
    - cargo fix --allow-dirty
    - cargo clippy --fix --allow-dirty
    - git config user.email "nfi005@uib.no"
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.com/path-to-project.git
    - git add .
    - git commit -m "Automated fixes by clippy, and cargo fix"
    - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again

test:
  stage: test
  image: neelzee/tauri_img
  script:
    - yarn install
    - yarn test
    - cd src-tauri
    - cargo test

pts:
  stage: push to svn
  image: neelzee/tauri_img
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
  dependencies:
    - "test"
  script:
    - ./pushToSvn.sh

windows-build:
  stage: build
  image: neelzee/tauri_img
  dependencies:
    - "pts"
  when: manual
  script:
    - yarn install
    - cargo install cargo-xwin
    - rustup component add clippy
    - cd src-tauri
    - cargo clippy --fix --bin "nmide"
    - cd ..
    - yarn tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc

debian-build:
  stage: build
  image: neelzee/tauri_img
  dependencies:
    - "pts"
  when: manual
  script:
    - yarn install
    - yarn tauri build

mac-build:
  stage: build
  image: neelzee/tauri_img
  dependencies:
    - "pts"
  when: manual
  script:
    - echo "TODO"
