stages:
  - test
  - svn
  - build

default:
  image: neelzee/nmide-tauri:latest

variables:
  CORE_OUT_DIR: "nmide-core/src-tauri/target/release/nmide"

rust_test:
  stage: test
  script:
    - echo "TODO"

js_test:
  stage: test
  script:
    - echo "TODO"

pts:
  stage: svn
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
  dependencies:
    - "js_test"
    - "rust_test"
  script:
    - echo "TODO"

pdf-build:
  image: neelzee/nmide-thesis:latest
  stage: build
  script:
    - pdflatex --output-directory=nmide-thesis nmide-thesis/main.tex
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - nmide-thesis/main.tex
  artifacts:
    when: on_success
    access: all
    paths:
      - nmide-thesis/*.pdf

windows-build:
  stage: build
  dependencies:
    - "pts"
  when: manual
  only:
    - main
  script:
    - echo "Needs a windows image"
  artifacts:
    when: on_success
    access: all
    paths:
      - $OUT_DIR

debian-build:
  stage: build
  dependencies:
    - "pts"
  when: manual
  only:
    - main
  script:
    - just build-release
  artifacts:
    when: on_success
    access: all
    paths:
      - $OUT_DIR

mac-build:
  stage: build
  dependencies:
    - "pts"
  when: manual
  only:
    - main
  script:
    - echo "TODO"
  artifacts:
    when: on_success
    access: all
    paths:
      - $OUT_DIR
