files = ["core/src-tauri/modules/ide_explorer/magnolia.png"]
rt-files = [
    "core/src-tauri/modules/rs-counter-plugin-example/rt-style.css",
    "core/src-tauri/modules/jsm-counter/js-style.css"
]

[modules]
trivial_module = { path = "core/src-tauri/modules/trivial_module/", enabled = true }
trivial_module_style = { kind = "css", path = "core/src-tauri/modules/trivial_module/", enabled = true }
magnolia_dependency = { path = "core/src-tauri/modules/magnolia_dependency/", enabled = true }
rust_dependency = { path = "core/src-tauri/modules/rust_dependency/", enabled = true }
ide_fsa = { path = "core/src-tauri/modules/ide_fsa/", enabled = true }
ide_framework = { path = "core/src-tauri/modules/ide_framework/", enabled = true }
ide_framework_style = { path = "core/src-tauri/modules/ide_framework/", kind = "css", enabled = true }
ide_pm = { path = "core/src-tauri/modules/ide_pm/", enabled = true }
ide_tabs = { path = "core/src-tauri/modules/ide_tabs/", enabled = true }
ide_tabs_style = { path = "core/src-tauri/modules/ide_tabs/", kind = "css", enabled = true }
ide_cache = { path = "core/src-tauri/modules/ide_cache/", enabled = true }
ide_pm_style = { path = "core/src-tauri/modules/ide_pm_style/", kind = "css", enabled = true }
ide_errors = { path = "core/src-tauri/modules/ide-errors/", package-manager = "bun", kind = "ts", enabled = true }
ide_explorer = { path = "core/src-tauri/modules/ide_explorer/", enabled = true }
ide_explorer_style = { path = "core/src-tauri/modules/ide_explorer/", kind = "css", enabled = true }
ide_explorer_expanded = { path = "core/src-tauri/modules/ide_explorer/", package-manager = "bun", kind = "ts", enabled = true }
ide-editor = { path = "core/src-tauri/modules/ide-editor/", package-manager = "bun", kind = "ts", enabled = true }
ide-editor-style = { path = "core/src-tauri/modules/ide-editor/", kind = "css", enabled = true }
dependency-viewer = { path = "core/src-tauri/modules/dependency-viewer", package-manager = "bun", kind = "mjs", enabled = true }
dependency-viewer-style = { path = "core/src-tauri/modules/dependency-viewer", kind = "css", enabled = true }
event_sender = { path = "core/src-tauri/modules/event_sender", kind = "ts", package-manager = "bun", enabled = true }
event_sender_style = { path = "core/src-tauri/modules/event_sender", kind = "css", enabled = true }
state_viz = { path = "core/src-tauri/modules/state_viz", kind = "ts", package-manager = "bun", enabled = true }
state_viz_style = { path = "core/src-tauri/modules/state_viz", kind = "css", enabled = true }
tab_wrapper = { path = "core/src-tauri/modules/tab_wrapper/", enabled = true }
module_installer = { path = "core/src-tauri/modules/module_installer/", enabled = true }
module_installer_style = { path = "core/src-tauri/modules/module_installer/", kind = "css", enabled = true }
ide_save = { path = "core/src-tauri/modules/ide_save/", kind = "ts", package-manager = "bun", enabled = true }

[rt-modules]
jsm-counter = { path = "core/src-tauri/modules/jsm-counter/", kind = "ts", package-manager = "bun", enabled = false }
rs-counter-plugin-example = { path = "core/src-tauri/modules/rs-counter-plugin-example/", enabled = false }
