// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Msg } from "./Msg";

export type Attr = { "Id": string } | { "Class": string } | { "Src": string } | { "Alt": string } | { "OnClick": Msg } | { "Attr": [string, string] };
