// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Style } from "./Style";
import type { StyleCondition } from "./StyleCondition";

export type Css = { styles: Array<[StyleCondition, Style]>, };
