// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Unit } from "./Unit";

export type Style = { "Width": [string, Unit] } | { "Height": [string, Unit] } | { "Padding": [string, Unit] } | { "PaddingTop": [string, Unit] } | { "PaddingLeft": [string, Unit] } | { "PaddingBottom": [string, Unit] } | { "PaddingRight": [string, Unit] } | { "Margin": [string, Unit] } | { "MarginTop": [string, Unit] } | { "MarginBottom": [string, Unit] } | { "MarginRight": [string, Unit] } | { "MarginLeft": [string, Unit] } | { "Color": Color } | { "BackgroundColor": Color };
