// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TSHtmlKind = "Div" | "P" | "H1" | "H2" | "H3" | "H4" | "H5" | "H6" | "Span" | "Section" | "Article" | "Aside" | "Audio" | "B" | "Br" | "Button" | "Code" | "Em" | "Fieldset" | "Form" | "Img" | "Input" | "Label" | "Link" | "Li" | "Menu" | "Nav" | "Ol" | "Option" | "Select" | "Style" | "Svg" | "Table" | "Td" | "Th" | "Ul" | "Video" | "Frag" | "Text";
