// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TSStyle = { width?: string | null, height?: string | null, padding?: string | null, paddingTop?: string | null, paddingBottom?: string | null, paddingRight?: string | null, paddingLeft?: string | null, marginTop?: string | null, marginBottom?: string | null, marginRight?: string | null, marginLeft?: string | null, color?: string | null, backgroundColor?: string | null, };
