// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Html } from "./Html";

export type State = Record<string, Value | undefined>;

export type Value =
  | "null"
  | { "int": number }
  | { "float": number }
  | { "bool": boolean }
  | { "str": string }
  | { "list": Array<Value> }
  | { "obj": Record<string, Value | undefined> }
  | { "html": Html };
