// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TMsg } from "./TMsg";

export type TAttr = { "id": string } | { "class": string } | { "style": string } | { "type": string } | { "checked": boolean } | { "onClick": TMsg } | { "onInput": TMsg } | { "emitInput": string } | { "src": string };
