[package]
name = "nmide-plugin"
version = "0.1.0"
edition = "2021"

[lib]
name = "nmide_plugin"
crate-type = ["cdylib", "rlib"]

[dependencies]
abi_stable = "0.11.3"
nmide-std-lib = { path = "../nmide-core/src-tauri/nmide-std-lib" }
