# Changelog

All notable changes to this project will be documented in this file.

## [1.0.0] - 2024-11-09

### 🚀 Features

- *(nmide-core)* Added Ord, Eq in Value and Map
- *(nmide-std-lib)* Added ts-auto-gen for Html
- *(nmide-core)* Enabled test coverage
- *(nmide-core)* Added chtml
- *(nmide-std-lib)* Added fn from Html to CHtml
- *(nmide-core)* Migrated to Tauri v2
- *(nmide-std-lib)* Implemented R* to T*
- *(nmide-std-lib)* Added merge_mut to rmap

### 🐛 Bug Fixes

- *(nmide-std-lib)* Corrected ts-export for types
- *(nmide-core)* Corrected RS-TS export path
- *(nmide-std-lib)* Updated lib for ease of use
- *(nmide-std-lib)* Corrected map methods

### 📚 Documentation

- *(nmide-std-lib)* Corrected code in doc-string

### 🧪 Testing

- *(nmide-std-lib)* Added Map parametarized tests

### ⚙️ Miscellaneous Tasks

- Update git
- *(nmide)* Added changelogs

<!-- generated by git-cliff -->
