// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TAttr } from "./TAttr";
import type { THtmlKind } from "./THtmlKind";

export type THtml = { kind: THtmlKind, kids: Array<THtml>, text: string | null, attrs: Array<TAttr>, };
