// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Consumer } from "./Consumer";
import type { Event } from "./Event";

export type NamedDependency = {
  name: string;
  providing: Array<Event>;
  consuming: Array<Consumer>;
  success: boolean;
};
