// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";

export type Attr = { "id": string } | { "class": string } | { "style": string } | { "type": string } | { "checked": boolean } | { "onClick": Event } | { "onInput": Event } | { "emitInput": Event } | { "src": string };
