// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Instruction<T> = "noOp" | { "add": [string, T] } | { "rem": [string, T] } | { "then": [Instruction<T>, Instruction<T>] };
