// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TMsg } from "./TMsg";

export type TAttr = { "Id": string } | { "Class": string } | { "Style": string } | { "OnClick": TMsg } | { "OnInput": TMsg } | { "EmitInput": string } | { "Src": string };
