// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type THtmlKind = "div" | "p" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "span" | "section" | "article" | "aside" | "audio" | "b" | "br" | "button" | "code" | "em" | "fieldset" | "form" | "img" | "input" | "label" | "link" | "li" | "menu" | "nav" | "ol" | "option" | "select" | "style" | "svg" | "table" | "td" | "th" | "tr" | "ul" | "video" | "frag" | "text" | "script" | "tbody";
