// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Element = "Div" | "P" | "Span" | "Section" | "Input" | "Button" | { "Text": string } | "Script" | "Select" | "Aside" | "Nav" | "A" | "None";
