[package]
name = "editor_buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
core-std-lib = { workspace = true }
core-module-lib = { workspace = true }
async-trait = "0.1.88"
editor-ar = { path = "../editor-ar" }
anyhow = "1.0.98"
