[package]
name = "rsm-grapher"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["rsm-handler", "rsm-invoker"]

[dependencies]
core-std-lib = { git = "https://github.com/Neelzee/nmide.git" }
core-module-lib = { git = "https://github.com/Neelzee/nmide.git" }
rsm-invoker = { path = "rsm-invoker" }
rsm-handler = { path = "rsm-handler" }
async-trait = "0.1.88"
tokio = { version = "1.44.2", features = ["full"] }
once_cell = "1.21.3"
futures = "0.3.31"
serde_json = "1.0.140"

# ============================================================================ #
