[package]
name = "rsm-grapher"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["rsm-handler", "rsm-invoker"]

[dependencies]
core-std-lib = { path = "../../../core/src-tauri/core-std-lib/" }
core-module-lib = { path = "../../../core/src-tauri/core-module-lib/" }
rsm-invoker = { path = "rsm-invoker" }
rsm-handler = { path = "rsm-handler" }
async-trait = "0.1.88"
tokio = { version = "1.44.2", features = ["full"] }
once_cell = "1.21.3"
futures = "0.3.31"
serde_json = "1.0.140"

# ============================================================================ #


[dependencies.ide_cache]
features = []
path = "/home/nmf/nmide/modules/ide_cache"


[dependencies.ide_explorer]
features = []
path = "/home/nmf/nmide/modules/ide_explorer"


[dependencies.ide_framework]
features = []
path = "/home/nmf/nmide/modules/ide_framework"


[dependencies.ide_fsa]
features = []
path = "/home/nmf/nmide/modules/ide_fsa"


[dependencies.ide_pm]
features = []
path = "/home/nmf/nmide/modules/ide_pm"


[dependencies.ide_tabs]
features = []
path = "/home/nmf/nmide/modules/ide_tabs"


[dependencies.magnolia_dependency]
features = []
path = "/home/nmf/nmide/modules/magnolia_dependency"


[dependencies.module_installer]
features = []
path = "/home/nmf/nmide/modules/module_installer"


[dependencies.tab_wrapper]
features = []
path = "/home/nmf/nmide/modules/tab_wrapper"


[dependencies.trivial_module]
features = []
path = "/home/nmf/nmide/modules/trivial_module"
