# Changelog

All notable changes to this Nmide JS-Library project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added

- Added lookup-or-default

### Changed

- Expanded appoptions
- Expanded window
- Cleanup is now a function
- Added new field on window
- Exposed root
- Added new field to window
- Version bump
- Updated bindings and Decoder
- Added TValueObj functions
- Version bump
- Updated TS-types
- Renamed nmide-js-utils

### Fixed

- Corrected typing on window
- Updated window
- Chaned MapBuilder export
- Added main-tag
- Corrected HtmlBuilder
- Updated T-types
- Fixed TMapPartialEq on empty TMap
- Corrected spelling
- Updated ViewDecoder
- Fix!(js-utils): Corrected TMapPartialEq
- Added tests for eq-functions
- Updated attributes
- Updated decoder

### Removed

- Removed unused imports

[unreleased]: https://github.com/Neelzee/Nmide/compare/v1.0.0..HEAD

<!-- generated by git-cliff -->
