[workspace]
members = ["nmide-macros", "nmide-plugin-manager", "nmide-std-lib"]

[package]
name = "core"
version = "1.0.0"
description = "A simple IDE"
authors = ["Nils Michael Fitjar <nfi005@uib.no>"]
license = ""
repository = "https://git.app.uib.no/Nils.Fitjar/nmide"
edition = "2021"

[build]
profiler = true

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }
dotenv = "0.15.0"

[dependencies]
tauri = { version = "2.1.1", features = ["protocol-asset", "config-toml"] }
serde = { version = "1.0.215", features = ["derive"] }
once_cell = "1.20.2"
tokio = { version = "1.41.1", features = ["full"] }
anyhow = "1.0.93"
nmide-std-lib = { path = "./nmide-std-lib" }
nmide-plugin-manager = { path = "./nmide-plugin-manager" }
libloading = "0.8.6"
anyhow-tauri = "1.0.0"
log = "0.4.22"
tauri-plugin-log = "2.0.2"
tauri-plugin-fs = "2.0.3"
tauri-plugin-shell = "2.0.2"
tauri-plugin-dialog = "2.0.3"
serde_json = "1.0.133"
abi_stable = "0.11.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
