[build-dependencies]
env = "1.0.1"
toml = "0.8.20"

[build-dependencies.tauri-build]
features = []
optional = true
version = "2.1.1"

[dependencies]
anyhow = "1.0.97"
log = "0.4.27"
once_cell = "1.21.3"
serde_json = "1.0.140"

[dependencies.actix-cors]
optional = true
version = "0.7.1"

[dependencies.actix-files]
optional = true
version = "0.6.6"

[dependencies.actix-web]
optional = true
version = "4.10.2"

[dependencies.anyhow-tauri]
optional = true
version = "1.0.0"

[dependencies.core-module-lib]
path = "./core-module-lib"

[dependencies.core-std-lib]
path = "./core-std-lib"

[dependencies.serde]
features = ["derive"]
version = "1.0.219"

[dependencies.tauri]
features = ["protocol-asset", "config-toml"]
optional = true
version = "2.4.1"

[dependencies.tauri-plugin-dialog]
optional = true
version = "2.2.1"

[dependencies.tauri-plugin-fs]
optional = true
version = "2.2.1"

[dependencies.tauri-plugin-log]
optional = true
version = "2.3.1"

[dependencies.tauri-plugin-shell]
optional = true
version = "2.2.1"

[dependencies.tokio]
features = ["full"]
version = "1.44.2"

[dependencies.trivial_module]
path = "../../plugins/trivial_module/"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = []
ide = ["dep:tauri", "dep:tauri-plugin-log", "dep:tauri-plugin-fs", "dep:tauri-plugin-shell", "dep:tauri-plugin-dialog", "dep:tauri-build"]
server = ["dep:actix-web", "dep:actix-files", "dep:actix-cors"]

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "core_lib"

[package]
authors = ["Nils Michael Fitjar <nfi005@uib.no>"]
description = "A simple, modular, IDE"
edition = "2021"
exclude = ["./core-*/*"]
license = "MIT License"
name = "core"
readme = "../../README.md"
repository = "https://github.com/Neelzee/nmide"
version = "1.1.0"

[workspace]
members = ["core-macros", "core-module-lib", "core-std-lib", "foreign-std-lib"]
