[workspace]
members = ["core-macros", "core-plugin-lib", "core-std-lib"]

[package]
name = "core"
version = "1.1.0"
description = "A simple IDE"
authors = ["Nils Michael Fitjar <nfi005@uib.no>"]
license = ""
repository = "https://git.app.uib.no/Nils.Fitjar/nmide"
edition = "2021"

[lib]
name = "core_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.3", features = [], optional = true }

[dependencies]
# IDE specific dependencies
tauri = { version = "2.1.1", features = [
  "protocol-asset",
  "config-toml",
], optional = true }
tauri-plugin-log = { version = "2.0.2", optional = true }
tauri-plugin-fs = { version = "2.0.3", optional = true }
tauri-plugin-shell = { version = "2.0.2", optional = true }
tauri-plugin-dialog = { version = "2.0.3", optional = true }
anyhow-tauri = { version = "1.0.0", optional = true }

# Server specific dependencies
actix-web = { version = "4.9.0", optional = true }
actix-files = { version = "0.6.6", optional = true }
actix-cors = { version = "0.7.0", optional = true }

serde = { version = "1.0.215", features = ["derive"] }
once_cell = "1.20.2"
tokio = { version = "1.41.1", features = ["full"] }
anyhow = "1.0.93"
core-std-lib = { path = "./core-std-lib" }
core-plugin-lib = { path = "./core-plugin-lib" }
log = "0.4.22"
serde_json = "1.0.133"

[features]
default = []
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
ide = [
  "dep:tauri",
  "dep:tauri-plugin-log",
  "dep:tauri-plugin-fs",
  "dep:tauri-plugin-shell",
  "dep:tauri-plugin-dialog",
  "dep:tauri-build",
]
server = ["dep:actix-web", "dep:actix-files", "dep:actix-cors"]
