[workspace]
members = ["core-macros", "core-module-lib", "core-std-lib", "foreign-std-lib"]

[package]
name = "core"
version = "1.1.0"
description = "A simple, modular, IDE"
authors = ["Nils Michael Fitjar <nfi005@uib.no>"]
license = "MIT License"
repository = "https://github.com/Neelzee/nmide"
edition = "2021"
readme = "../../README.md"
exclude = ["./core-*/*"]

[lib]
name = "core_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.1.1", features = [], optional = true }

[dependencies]
# IDE specific dependencies
tauri = { version = "2.4.1", features = [
  "protocol-asset",
  "config-toml",
], optional = true }
tauri-plugin-log = { version = "2.3.1", optional = true }
tauri-plugin-fs = { version = "2.2.1", optional = true }
tauri-plugin-shell = { version = "2.2.1", optional = true }
tauri-plugin-dialog = { version = "2.2.1", optional = true }
anyhow-tauri = { version = "1.0.0", optional = true }

# Server specific dependencies
actix-web = { version = "4.10.2", optional = true }
actix-files = { version = "0.6.6", optional = true }
actix-cors = { version = "0.7.1", optional = true }

serde = { version = "1.0.219", features = ["derive"] }
once_cell = "1.21.3"
tokio = { version = "1.44.1", features = ["full"] }
anyhow = "1.0.97"
core-std-lib = { path = "./core-std-lib" }
core-module-lib = { path = "./core-module-lib" }
log = "0.4.27"
serde_json = "1.0.140"

[features]
default = []
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
ide = [
  "dep:tauri",
  "dep:tauri-plugin-log",
  "dep:tauri-plugin-fs",
  "dep:tauri-plugin-shell",
  "dep:tauri-plugin-dialog",
  "dep:tauri-build",
]
server = ["dep:actix-web", "dep:actix-files", "dep:actix-cors"]
