productName = "nmide-dev"
mainBinaryName = "nmide-dev"
version = "1.0.0"
identifier = "no.nilsmf.uib"

[build]
beforeDevCommand = "cargo run --manifest-path=./src-tauri/core-cm-installer/Cargo.toml -- --out=./src-tauri/target --conf=./modules/Modules.toml --cargo=./src-tauri/Cargo.toml && bun run dev"
beforeBuildCommand = "cargo run --manifest-path=./src-tauri/core-cm-installer/Cargo.toml -- --out=./src-tauri/target --conf=./modules/Modules.toml --cargo=./src-tauri/Cargo.toml && bun run build"
devUrl = "http://localhost:5173"
frontendDist = "../dist"

[bundle]
active = true
targets = "all"
longDescription = "A simple modular Integrated Development Environment"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
resources = []
category = "DeveloperTool"
shortDescription = "A simple IDE"

[plugins]

[app.security]
csp = "asset: https://asset.localhost; connect-src ipc: http://ipc.localhost"
capabilities = ["nmide-capabilities"]

[app.security.assetProtocol]
scope = ["$APPDATA/modules/*"]
enable = true

[[app.windows]]
title = "nmide"
width = 800
height = 600
