# Changelog

All notable changes to Nmide-Core Macros will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Changed

- Updated cliff config
- Changed name

### Removed

- Removed nmide prefix

## [1.0.0] - 2024-11-09

### Added

- Added chtml
- Added cast_html method to Html

### Changed

- Bump version
- Merge branch 'dev' into 'main'
- Merge branch 'NC-TS-Plugins' into 'dev'
- Migrated to Tauri v2
- Enabled test coverage
- Added Ord, Eq in Value and Map
- Feat!(nmide-std-lib): implemented nmide-std-lib

### Fixed

- Fix!(nmide-core): fixed technical debt per #47
- Corrected ts-export for types

[unreleased]: https://github.com/Neelzee/Nmide/compare/v1.0.0..HEAD
[1.0.0]: https://github.com/Neelzee/Nmide/compare/v0.2.0..v1.0.0

<!-- generated by git-cliff -->
