[package]
name = "ide-fsa"
version = "0.1.0"
edition = "2021"

[lib]
name = "ide_fsa"
crate-type = ["cdylib", "rlib"]

[dependencies]
abi_stable = "0.11.3"
anyhow = "1.0.94"
core-std-lib = { path = "../../core/src-tauri/core-std-lib" }
once_cell = "1.20.2"
regex = { version = "1.11.1", features = ["std"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
