[modules]
trivial_module = { path = "../modules/trivial_module/", enabled = false }
magnolia_dependency = { path = "../modules/magnolia_dependency/", enabled = false }
ide_fsa = { path = "../modules/ide_fsa/", enabled = false }
ide_framework = { path = "../modules/ide_framework/", enabled = false }
ide_framework_style = { path = "../modules/ide_framework/", kind = "css", enabled = false }
ide_pm = { path = "../modules/ide_pm/", enabled = false }
ide_tabs = { path = "../modules/ide_tabs/", enabled = false }
ide_tabs_style = { path = "../modules/ide_tabs/", kind  = "css", enabled = false }
ide_cache = { path = "../modules/ide_cache/", enabled = false }
ide_pm_style = { path = "../modules/ide_pm_style/", kind = "css", enabled = false }
ide_errors = { path = "../modules/ide-errors/", package-manager = "bun", kind = "ts", enabled = false }
ide-editor = { path = "../modules/ide-editor/", package-manager = "bun", kind = "ts", enabled = false }
rs-counter-plugin-example = { path = "../modules/rs-counter-plugin-example/", kind = "so", enabled = false }
dependency-viewer = { path = "../modules/dependency-viewer", package-manager = "bun", kind = "mjs", enabled = false }
dependency-viewer-style = { path = "../modules/dependency-viewer", kind = "css", enabled = false }
event_sender = { path = "../modules/event_sender", kind = "ts", package-manager = "bun", enabled = true }
event_sender_style = { path = "../modules/event_sender", kind = "css", enabled = true }
