files = ["../modules/ide_explorer/magnolia.png"]

[modules]
trivial_module = { path = "../modules/trivial_module/", enabled = true }
trivial_module_style = { kind = "css", path = "../modules/trivial_module/", enabled = true }
magnolia_dependency = { path = "../modules/magnolia_dependency/", enabled = true }
ide_fsa = { path = "../modules/ide_fsa/", enabled = true }
ide_framework = { path = "../modules/ide_framework/", enabled = true }
ide_framework_style = { path = "../modules/ide_framework/", kind = "css", enabled = true }
ide_pm = { path = "../modules/ide_pm/", enabled = true }
ide_tabs = { path = "../modules/ide_tabs/", enabled = true }
ide_tabs_style = { path = "../modules/ide_tabs/", kind = "css", enabled = true }
ide_cache = { path = "../modules/ide_cache/", enabled = true }
ide_pm_style = { path = "../modules/ide_pm_style/", kind = "css", enabled = true }
ide_errors = { path = "../modules/ide-errors/", package-manager = "bun", kind = "ts", enabled = true }
ide_explorer = { path = "../modules/ide_explorer/", enabled = true }
ide_explorer_style = { path = "../modules/ide_explorer/", kind = "css", enabled = true }
ide_explorer_expanded = { path = "../modules/ide_explorer/", package-manager = "bun", kind = "ts", enabled = true }
ide-editor = { path = "../modules/ide-editor/", package-manager = "bun", kind = "ts", enabled = true }
ide-editor-style = { path = "../modules/ide-editor/", kind = "css", enabled = true }
rs-counter-plugin-example = { path = "../modules/rs-counter-plugin-example/", kind = "so", enabled = true }
dependency-viewer = { path = "../modules/dependency-viewer", package-manager = "bun", kind = "mjs", enabled = true }
dependency-viewer-style = { path = "../modules/dependency-viewer", kind = "css", enabled = true }
event_sender = { path = "../modules/event_sender", kind = "ts", package-manager = "bun", enabled = true }
event_sender_style = { path = "../modules/event_sender", kind = "css", enabled = true }
state_viz = { path = "../modules/state_viz", kind = "ts", package-manager = "bun", enabled = true }
state_viz_style = { path = "../modules/state_viz", kind = "css", enabled = true }
tab_wrapper = { path = "../modules/tab_wrapper/", enabled = true }
module_installer = { path = "../modules/module_installer/", enabled = true }
module_installer_style = { path = "../modules/module_installer/", kind = "css", enabled = true }
ide_save = { path = "../modules/ide_save/", kind = "ts", package-manager = "bun", enabled = true }
