productName = "mini-core"
mainBinaryName = "mini-core"
version = "1.0.0"
identifier = "no.nilsmf.mini-core.uib"

[build]
beforeDevCommand = "make nmide && bun run dev"
beforeBuildCommand = "make nmide && bun run build"
devUrl = "http://localhost:5173"
frontendDist = "../dist"

[bundle]
active = true
targets = "all"
longDescription = "A simple modular module tester"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
resources = []
category = "DeveloperTool"
shortDescription = "A simple module tester"

[plugins]

[app.security]
csp = "asset: https://asset.localhost; connect-src ipc: http://ipc.localhost"
capabilities = ["nmide-capabilities"]

[app.security.assetProtocol]
scope = ["$APPDATA/modules/*"]
enable = true

[[app.windows]]
title = "nmide"
width = 800
height = 600
