/* tslint:disable */
/* eslint-disable */
/**
 * nmide API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Folder } from './Folder';
import {
    instanceOfFolder,
    FolderFromJSON,
    FolderFromJSONTyped,
    FolderToJSON,
} from './Folder';
import type { ModelFile } from './ModelFile';
import {
    instanceOfModelFile,
    ModelFileFromJSON,
    ModelFileFromJSONTyped,
    ModelFileToJSON,
} from './ModelFile';

/**
 * @type FolderOrFile
 * 
 * @export
 */
export type FolderOrFile = Folder | ModelFile;

export function FolderOrFileFromJSON(json: any): FolderOrFile {
    return FolderOrFileFromJSONTyped(json, false);
}

export function FolderOrFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderOrFile {
    if (json == null) {
        return json;
    }
    if (instanceOfFolder(json)) {
        return FolderFromJSONTyped(json, true);
    }
    if (instanceOfModelFile(json)) {
        return ModelFileFromJSONTyped(json, true);
    }
}

export function FolderOrFileToJSON(value?: FolderOrFile | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfFolder(value)) {
        return FolderToJSON(value as Folder);
    }
    if (instanceOfModelFile(value)) {
        return ModelFileToJSON(value as ModelFile);
    }

    return {};
}

