/* tslint:disable */
/* eslint-disable */
/**
 * nmide API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Any } from './Any';
import {
    AnyFromJSON,
    AnyFromJSONTyped,
    AnyToJSON,
} from './Any';
import type { NmideReport } from './NmideReport';
import {
    NmideReportFromJSON,
    NmideReportFromJSONTyped,
    NmideReportToJSON,
} from './NmideReport';

/**
 * 
 * @export
 * @interface NmideError
 */
export interface NmideError {
    /**
     * 
     * @type {Any}
     * @memberof NmideError
     */
    val: Any;
    /**
     * 
     * @type {NmideReport}
     * @memberof NmideError
     */
    rep?: NmideReport;
}

/**
 * Check if a given object implements the NmideError interface.
 */
export function instanceOfNmideError(value: object): value is NmideError {
    if (!('val' in value) || value['val'] === undefined) return false;
    return true;
}

export function NmideErrorFromJSON(json: any): NmideError {
    return NmideErrorFromJSONTyped(json, false);
}

export function NmideErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): NmideError {
    if (json == null) {
        return json;
    }
    return {
        
        'val': AnyFromJSON(json['val']),
        'rep': json['rep'] == null ? undefined : NmideReportFromJSON(json['rep']),
    };
}

export function NmideErrorToJSON(value?: NmideError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'val': AnyToJSON(value['val']),
        'rep': NmideReportToJSON(value['rep']),
    };
}

