[package]
name = "ide_cache"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
core-std-lib = { workspace = true }
core-module-lib = { workspace = true }
serde_json = "1.0.140"
