[package]
name = "nmide-std-lib"
version = "0.1.0"
edition = "2021"

[build]
profiler = true

[dependencies]
abi_stable = "0.11.3"
nmide-macros = { path = "../nmide-macros/" }
once_cell = "1.20.2"
rstest = "0.23.0"
serde = { version = "1.0.210", features = ["derive"] }
stabby = "36.1.1"
ts-rs = "10.0.0"
