[package]
name = "nmide-std-lib"
version = "0.1.0"
edition = "2021"

[build]
profiler = true

[dependencies]
abi_stable = "0.11.3"
nmide-macros = { path = "../nmide-macros/" }
rstest = "0.22.0"
serde = { version = "1.0.208", features = ["derive"] }
stabby = "36.1.1"
ts-rs = "9.0.1"
