// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TValue } from "./TValue";

export type TMap = { map: Array<[string, TValue]>, };
