// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TEvent } from "./TEvent";

export type TAttr = { "id": string } | { "class": string } | { "style": string } | { "type": string } | { "checked": boolean } | { "onClick": TEvent } | { "onInput": TEvent } | { "emitInput": string } | { "src": string };
