[package]
name = "rsm-invoker"
version = "0.1.0"
edition = "2024"

[dependencies]
core-std-lib = { workspace = true }
core-module-lib = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }
once_cell = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
ts-rs = { workspace = true }
