[package]
name = "nmide-rust-ffi"
version = "0.1.3-alpha"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.86"
c_vec = "2.0.0"
safer-ffi.features = ["alloc"]
safer-ffi.version = "0.1.9"
serde.features = ["derive"]
serde.version = "1.0.204"
serde_json = "1.0.121"
ts-rs = "9.0.1"

[build-dependencies]
cmake = "0.1.31"
