[package]
name = "nmide-rust-ffi"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.86"
c_vec = "2.0.0"
rstest = "0.22.0"
safer-ffi = { version = "0.1.9", features = ["alloc"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
nmide-std-lib = { path = "../../nmide-core/src-tauri/nmide-std-lib" }

[build-dependencies]
bindgen = "0.69.4"
anyhow = "1.0.86"

[lib]
name = "nmide_rust_ffi"
crate-type = ["rlib", "staticlib"]
