[package]
name = "core-std-lib"
version = "2.0.2"
edition = "2021"

[lib]
name = "core_std_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
abi_stable = "0.11.3"
core-macros = { path = "../core-macros/" }
once_cell = "1.20.2"
rstest = "0.23.0"
serde = { version = "1.0.214", features = ["derive"] }
stabby = { version = "36.1.1", optional = true }
ts-rs = { version = "10.0.0", optional = true }

[features]
default = ["ts"]
c = ["dep:stabby"]
ts = ["dep:ts-rs"]
