[package]
name = "core-std-lib"
version = "1.0.0"
edition = "2021"

[dependencies]
abi_stable = "0.11.3"
core-macros = { path = "../core-macros/" }
once_cell = "1.20.2"
rstest = "0.23.0"
serde = { version = "1.0.214", features = ["derive"] }
stabby = "36.1.1"
ts-rs = "10.0.0"
