[package]
name = "core-std-lib"
version = "2.0.2"
edition = "2021"

[lib]
name = "core_std_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
core-macros = { path = "../core-macros/" }
once_cell = "1.20.2"
rstest = "0.25.0"
