[build]
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"
devPath = "http://localhost:1420"
distDir = "../dist"

[package]
productName = "nmide"
version = "0.1.0"

[tauri.allowlist]
all = false

[tauri.allowlist.shell]
all = false
open = true

[tauri.allowlist.fs]
scope = [ "$APPCONFIG/*", "$APPDATA/*", "$APPLOG/*", "$APPCACHE/*" ]
readFile = true
readDir = true

[[tauri.windows]]
title = "nmide"
width = 800
height = 600

[tauri.security]

[tauri.bundle]
active = true
targets = "all"
identifier = "no.nilsmf.uib"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
resources = [ ]
category = "DeveloperTool"
shortDescription = "A simple IDE"
longDescription = "A simple modular Integrated Developert Environment"
