productName = "nmide"
mainBinaryName = "nmide"
version = "0.1.0"
identifier = "no.nilsmf.uib"

[build]
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"
devUrl = "http://localhost:3000"
frontendDist = "../.next/server/app/"

[bundle]
active = true
targets = "all"
longDescription = "A simple modular Integrated Development Environment"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
resources = []
category = "DeveloperTool"
shortDescription = "A simple IDE"

[plugins]

[app.security]
csp = "asset: https://asset.localhost; connect-src ipc: http://ipc.localhost"
capabilities = ["nmide-capabilities"]

[app.security.assetProtocol]
scope = ["$APPDATA/plugins/*"]
enable = true

[[app.windows]]
title = "nmide"
width = 800
height = 600
