[package]
name = "nmide-plugin-manager"
version = "0.1.0"
authors = ["Nils Michael Fitjar <nfi005@uib.no>"]
edition = "2021"

[build]
profiler = true

[dependencies]
anyhow = "1.0.86"
libloading = "0.8.5"
nmide-std-lib = { path = "../nmide-std-lib" }
log = "0.4.22"
abi_stable = "0.11.3"
