[package]
name = "nmide-plugin-manager"
version = "0.1.0"
authors = ["Nils Michael Fitjar <nfi005@uib.no>"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
libloading = "0.8.5"
nmide-rust-ffi.path = "../../../nmide-wrapper/nmide-rust-ffi"
safer-ffi = "0.1.12"
either = { version = "1.13.0", features = ["serde"] }
log = "0.4.22"
