// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TValue } from "./TMap";

export type TEvent = { eventName: string, moduleName: string, args: TValue | null, };
