// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attr } from "./Attr";
import type { TSHtmlKind } from "../../src/bindings/TSHtmlKind";

export type TSHtml = { kind: TSHtmlKind, kids: Array<TSHtml>, text: string | null, attrs: Array<Attr>, };
