// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Value = { "Int": number } | { "Float": number } | { "Bool": boolean } | { "String": string } | { "List": Array<Value> } | { "Object": Array<[string, Value]> };
