// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attr } from "./Attr";
import type { Html } from "./Html";
import type { Instruction } from "./Instruction";
import type { Value } from "./State";

export type CoreModification = {
  state: Instruction<Value>;
  ui: [Instruction<Html>, Instruction<string>, Instruction<Attr>];
};
