// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attr } from "./Attr";

export type Html =
  | { "div": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "p": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "h1": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "h2": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "h3": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "h4": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "h5": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "h6": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "span": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | {
    "section": { kids: Array<Html>; attrs: Array<Attr>; text: string | null };
  }
  | {
    "article": { kids: Array<Html>; attrs: Array<Attr>; text: string | null };
  }
  | { "aside": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "audio": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "b": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "br": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "strong": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "button": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "code": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "em": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | {
    "fieldset": { kids: Array<Html>; attrs: Array<Attr>; text: string | null };
  }
  | { "form": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "img": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "input": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "label": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "link": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "li": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "menu": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "nav": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "ol": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "option": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "select": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "style": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "svg": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "table": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "td": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "th": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "tr": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "ul": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "video": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "frag": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "script": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "thead": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "tbody": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | { "main": { kids: Array<Html>; attrs: Array<Attr>; text: string | null } }
  | {
    "textArea": { kids: Array<Html>; attrs: Array<Attr>; text: string | null };
  };
