name: Lib-Unit-Tests

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-js-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build
        run: make init && make install-deps && cd core && bun i
      - name: Run tests
        run: cd libs/javascript/decoder-lib && bun i && bun run test --run
  test-rs-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make install-deps
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run tests
        run: cd libs/rust/ && cargo test --workspace
