name: Core-Unit-Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd core && npm i
    - name: Run tests
      run: cd core npm run test
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd core/src-tauri/ && cargo build --verbose --workspace
    - name: Run tests
      run: cd core/src-tauri/ && cargo test --verbose --workspace
